export const AUTH_LOGIN_START = 'LOGIN_START';
export const AUTH_LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const AUTH_LOGIN_FAIL = 'LOGIN_FAIL';
export const AUTH_LOGOUT = 'LOGIN_LOGOUT';

export const AUTH_SIGNUP_START = 'SIGNUP_START';
export const AUTH_SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const AUTH_SIGNUP_FAIL = 'SIGNUP_FAIL';

export const SET_AUTH_PATH_REDIRECT = 'SET_AUTH_PATH_REDIRECT';